config/routes.rb
Rails.application.routes.draw do
  get 'downvotes/create'
  get 'upvotes/create'
  devise_for :users

  resources :posts do
    member do
      post "upvote", to: "upvotes#create"
      post "downvote", to: "downvotes#create"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  broadcasts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  acts_as_voter

  def upvote!(obj)
    if voted_up_for? obj
      unlike obj
    else
      upvotes obj
    end
  end

  def downvote!(obj)
    if voted_down_for? obj
      unlike obj
    else
      downvotes obj
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/downvotes_controller.rb
class DownvotesController < VotingController
  def create
    respond_to do |format|
      current_user.downvote! @object
      format.html { render @object }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy toggle_upvote toggle_downvote ]
  before_action :authenticate_user!, only: %i[ toggle_upvote toggle_downvote ]

  def toggle_upvote
    current_user.favorited?(@post) ? current_user.unfavorite(@post) : current_user.favorite(@post)
  end
  
  def toggle_downvote
    current_user.favorited?(@post) ? current_user.unfavorite(@post) : current_user.favorite(@post)
  end

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/upvotes_controller.rb
class UpvotesController < VotingController
  def create
    respond_to do |format|
      current_user.upvote! @object
      format.html { render @object }
    end
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/voting_controller.rb
class VotingController < ApplicationController
  before_action :set_object
  before_action :authenticate_user!

  def set_object
    @object = GlobalID::Locator.locate(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UppieDownie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_devise.html.erb
<% unless user_signed_in? %>
  <%= link_to t("devise.sessions.log_in"), new_user_session_path %>
  <%= link_to t("devise.registrations.register_now"), new_user_registration_path %>
<% else %>
  <%= link_to t("devise.registrations.my_account"), edit_user_registration_path %>
  <%= link_to t("devise.sessions.log_out"), destroy_user_session_path, method: :delete %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_stream_from @post %>
<%= turbo_frame_tag(post) do %>

  <%= button_to "UpVote", upvote_post_path(post.to_global_id) %>

  <p>
    <strong>Score:</strong>
    <%= post.weighted_score %>
  </p>

  <%= button_to "DownVote", downvote_post_path(post.to_global_id) %>

  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<%= render partial: "devise" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @post %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<%= render partial: "devise" %>

app/views/posts/toggle_downvote.js.erb
var postId = "<%= @post.id %>";

function toggleDownvote(postId, innerHTML) {
  let downvote = document.querySelector(`.downvote[data-id="${ postId }"]`);
  downvote.classList.toggle("active");
}

toggleDownvote(postId);

app/views/posts/toggle_upvote.js.erb
var postId = "<%= @post.id %>";

function toggleUpvote(postId, innerHTML) {
  let upvote = document.querySelector(`.upvote[data-id="${ postId }"]`);
  upvote.classList.toggle("active");
}

toggleUpvote(postId);